# Generated by Django 4.0.2 on 2022-03-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iptableRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('rule', models.CharField(max_length=200)),
                ('ipaddr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='wafdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=200)),
                ('container_name', models.CharField(max_length=200)),
                ('container_port', models.CharField(max_length=200)),
                ('container_ip', models.CharField(max_length=200)),
                ('public_ip', models.CharField(max_length=200)),
            ],
        ),
    ]
