# Generated by Django 4.0.2 on 2022-03-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_iptablerules_wafdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='wafdetails',
            name='project_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
