# Generated by Django 4.0.2 on 2022-04-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_wafdetails_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQlFileterRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('SQLFilterStr', models.CharField(max_length=200)),
            ],
        ),
    ]
